import sqlalchemy

engine = sqlalchemy.create_engine('postgresql://polemos87:19871505@localhost:5432/db1')
connection = engine.connect()

connection.execute("""INSERT INTO genre(name)
    VALUES('Rock');""")
connection.execute("""INSERT INTO genre(name)
    VALUES('Metal');""")
connection.execute("""INSERT INTO genre(name)
    VALUES('Pop');""")
connection.execute("""INSERT INTO genre(name)
    VALUES('Rap');""")
connection.execute("""INSERT INTO genre(name)
    VALUES('Jazz');""")

connection.execute("""INSERT INTO artists(name)
    VALUES('The Beatles');""")
connection.execute("""INSERT INTO artists(name)
    VALUES('Radiohead');""")
connection.execute("""INSERT INTO artists(name)
    VALUES('Metallica');""")
connection.execute("""INSERT INTO artists(name)
    VALUES('Rammstein');""")
connection.execute("""INSERT INTO artists(name)
    VALUES('Madonna');""")
connection.execute("""INSERT INTO artists(name)
    VALUES('Britney Spears');""")
connection.execute("""INSERT INTO artists(name)
    VALUES('Eminem');""")
connection.execute("""INSERT INTO artists(name)
    VALUES('Snoop Dogg');""")
connection.execute("""INSERT INTO artists(name)
    VALUES('John Coltrane');""")
connection.execute("""INSERT INTO artists(name)
    VALUES('Louis Armstrong');""")

connection.execute("""INSERT INTO albums(name, release)
    VALUES('Beatles For Sale', 1964);""")
connection.execute("""INSERT INTO albums(name, release)
    VALUES('The King of Limbs', 2011);""")
connection.execute("""INSERT INTO albums(name, release)
    VALUES('And Justice for All', 1988);""")
connection.execute("""INSERT INTO albums(name, release)
    VALUES('Rosenrot', 2005);""")
connection.execute("""INSERT INTO albums(name, release)
    VALUES('Rammstein!', 2019);""")
connection.execute("""INSERT INTO albums(name, release)
    VALUES('Femme Fatale', 2011);""")
connection.execute("""INSERT INTO albums(name, release)
    VALUES('Kamikaze', 2018);""")
connection.execute("""INSERT INTO albums(name, release)
    VALUES('Revival!', 2017);""")
connection.execute("""INSERT INTO albums(name, release)
    VALUES(' Get Yo Bread Up', 2018);""")
connection.execute("""INSERT INTO albums(name, release)
    VALUES('Stardust', 1958);""")
connection.execute("""INSERT INTO albums(name, release)
    VALUES('Satchmo in Style', 1959);""")
connection.execute("""INSERT INTO albums(name, release)
    VALUES('Madam X', 2019);""")

connection.execute("""INSERT INTO composition(name, duration, albums_id)
    VALUES('No Reply' ,'02:15', 1);""")
connection.execute("""INSERT INTO composition(name, duration, albums_id)
    VALUES('I’m a Loser' ,'2:28', 1);""")
connection.execute("""INSERT INTO composition(name, duration, albums_id)
    VALUES('…And Justice for All' ,'9:45', 3);""")
connection.execute("""INSERT INTO composition(name, duration, albums_id)
    VALUES('Dyers Eve' ,'5:13', 3);""")
connection.execute("""INSERT INTO composition(name, duration, albums_id)
    VALUES('Bloom' ,'5:15', 2);""")
connection.execute("""INSERT INTO composition(name, duration, albums_id)
    VALUES('Feral','3:13', 2);""")
connection.execute("""INSERT INTO composition(name, duration, albums_id)
    VALUES('Benzin','3:46', 4);""")
connection.execute("""INSERT INTO composition(name, duration, albums_id)
    VALUES('Rammstein','3:26', 5);""")
connection.execute("""INSERT INTO composition(name, duration, albums_id)
    VALUES('Till the World Ends','3:26' ,6);""")
connection.execute("""INSERT INTO composition(name, duration, albums_id)
    VALUES('How I Roll', '3:56', 6);""")
connection.execute("""INSERT INTO composition(name, duration, albums_id)
    VALUES('The Ringer','5:37', 7);""")
connection.execute("""INSERT INTO composition(name, duration, albums_id)
    VALUES('Normal','3:37', 7);""")
connection.execute("""INSERT INTO composition(name, duration, albums_id)
    VALUES('Roaches In My Ashtray', '4:56', 9);""")
connection.execute("""INSERT INTO composition(name, duration, albums_id)
    VALUES(' Get Yo Bread Up', '3:46', 9);""")
connection.execute("""INSERT INTO composition(name, duration, albums_id)
    VALUES('Love Thy Neighbor', '9:56' ,10);""")
connection.execute("""INSERT INTO composition(name, duration, albums_id)
    VALUES('Time After Time', '8:57', 10);""")
connection.execute("""INSERT INTO composition(name, duration, albums_id)
    VALUES('Jeannine ', '3:26', 11);""")
connection.execute("""INSERT INTO composition(name, duration, albums_id)
    VALUES('You are Just in Love', '2:43', 11);""")
connection.execute("""INSERT INTO composition(name, duration, albums_id)
    VALUES('God Control',' 6:19', 12);""")
connection.execute("""INSERT INTO composition(name, duration, albums_id)
    VALUES('Crazy', '4:02', 12);""")

connection.execute("""INSERT INTO collection(name, release)
    VALUES('first', 2019);""")
connection.execute("""INSERT INTO collection(name, release)
    VALUES('second', 2010);""")
connection.execute("""INSERT INTO collection(name, release)
    VALUES('third', 2020);""")
connection.execute("""INSERT INTO collection(name, release)
    VALUES('fourth', 2011);""")
connection.execute("""INSERT INTO collection(name, release)
    VALUES('fifth', 1970);""")
connection.execute("""INSERT INTO collection(name, release)
    VALUES('sixth', 2001);""")
connection.execute("""INSERT INTO collection(name, release)
    VALUES('seventh', 2012);""")
connection.execute("""INSERT INTO collection(name, release)
    VALUES('eighth', 1987);""")


connection.execute("""INSERT INTO artisgenre(artist_id, genre_id)
 VALUES(1, 1);""")
connection.execute("""INSERT INTO artisgenre(artist_id, genre_id)
    VALUES(1, 3);""")
connection.execute("""INSERT INTO artisgenre(artist_id, genre_id)
    VALUES(2, 1);""")
connection.execute("""INSERT INTO artisgenre(artist_id, genre_id)
    VALUES(3, 2);""")
connection.execute("""INSERT INTO artisgenre(artist_id, genre_id)
    VALUES(4, 2);""")
connection.execute("""INSERT INTO artisgenre(artist_id, genre_id)
    VALUES(5, 3);""")
connection.execute("""INSERT INTO artisgenre(artist_id, genre_id)
    VALUES(6, 3);""")
connection.execute("""INSERT INTO artisgenre(artist_id, genre_id)
    VALUES(7, 4);""")
connection.execute("""INSERT INTO artisgenre(artist_id, genre_id)
    VALUES(8, 4);""")
connection.execute("""INSERT INTO artisgenre(artist_id, genre_id)
    VALUES(9, 5);""")
connection.execute("""INSERT INTO artisgenre(artist_id, genre_id)
    VALUES(10, 5);""")

connection.execute("""INSERT INTO artistsalbums(artist_id, albums_id)
    VALUES(1, 1);""")
connection.execute("""INSERT INTO artistsalbums(artist_id, albums_id)
    VALUES(2, 2);""")
connection.execute("""INSERT INTO artistsalbums(artist_id, albums_id)
    VALUES(3, 3);""")
connection.execute("""INSERT INTO artistsalbums(artist_id, albums_id)
    VALUES(4, 4);""")
connection.execute("""INSERT INTO artistsalbums(artist_id, albums_id)
    VALUES(4, 5);""")
connection.execute("""INSERT INTO artistsalbums(artist_id, albums_id)
    VALUES(5, 12);""")
connection.execute("""INSERT INTO artistsalbums(artist_id, albums_id)
    VALUES(6, 6);""")
connection.execute("""INSERT INTO artistsalbums(artist_id, albums_id)
    VALUES(7, 7);""")
connection.execute("""INSERT INTO artistsalbums(artist_id, albums_id)
    VALUES(7, 8);""")
connection.execute("""INSERT INTO artistsalbums(artist_id, albums_id)
    VALUES(8, 9);""")
connection.execute("""INSERT INTO artistsalbums(artist_id, albums_id)
    VALUES(9, 10);""")
connection.execute("""INSERT INTO artistsalbums(artist_id, albums_id)
    VALUES(10, 11);""")

connection.execute("""INSERT INTO compositioncollection(composition_id, collection_id)
    VALUES(1, 1);""")
connection.execute("""INSERT INTO compositioncollection(composition_id, collection_id)
    VALUES(3, 1);""")
connection.execute("""INSERT INTO compositioncollection(composition_id, collection_id)
    VALUES(2, 2);""")
connection.execute("""INSERT INTO compositioncollection(composition_id, collection_id)
    VALUES(4, 2);""")
connection.execute("""INSERT INTO compositioncollection(composition_id, collection_id)
    VALUES(5, 3);""")
connection.execute("""INSERT INTO compositioncollection(composition_id, collection_id)
    VALUES(7, 3);""")
connection.execute("""INSERT INTO compositioncollection(composition_id, collection_id)
    VALUES(6, 4);""")
connection.execute("""INSERT INTO compositioncollection(composition_id, collection_id)
    VALUES(8, 4);""")
connection.execute("""INSERT INTO compositioncollection(composition_id, collection_id)
    VALUES(9, 5);""")
connection.execute("""INSERT INTO compositioncollection(composition_id, collection_id)
    VALUES(11, 5);""")
connection.execute("""INSERT INTO compositioncollection(composition_id, collection_id)
    VALUES(10, 6);""")
connection.execute("""INSERT INTO compositioncollection(composition_id, collection_id)
    VALUES(12, 6);""")
connection.execute("""INSERT INTO compositioncollection(composition_id, collection_id)
    VALUES(13, 7);""")
connection.execute("""INSERT INTO compositioncollection(composition_id, collection_id)
    VALUES(15, 7);""")
connection.execute("""INSERT INTO compositioncollection(composition_id, collection_id)
    VALUES(16, 8);""")
connection.execute("""INSERT INTO compositioncollection(composition_id, collection_id)
    VALUES(18, 8);""")
